config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:destroy]
  resources :sessions, only: [:new, :create]
  resources :opinions do
    resources :comments, except: [:new, :index, :show]
    resources :likings, only: [:create, :update]
  end
  get '/sign-up', to: 'users#new'
  get '/sign-in', to: 'sessions#new'
  get '/sign-out', to: 'sessions#destroy'
  post '/follow/:id', to: 'users#follow'
  delete '/unfollow/:id', to: 'users#unfollow'
  root 'opinions#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates_uniqueness_of :username
  validates :fullname, presence: true, length: { minimum: 5, maximum: 50 }
  validates :username, presence: true, length: { minimum: 5, maximum: 10 }
  validates :photo, presence: true
  validates :cover_image, presence: true

  scope :all_users_except_me, ->(user) { where.not(id: user).includes(:photo_attachment) }

  has_one_attached :photo
  has_one_attached :cover_image

  has_many :sent_followings, class_name: 'Following', foreign_key: 'follower_id'
  has_many :recieved_followings, class_name: 'Following', foreign_key: 'followed_id'
  has_many :followers, through: :recieved_followings, source: :follower
  has_many :followeds, through: :sent_followings, source: :followed

  has_many :opinions, foreign_key: 'author_id'

  has_many :comments, foreign_key: 'author_id'
  has_many :commented_opinions, through: :comments, source: :opinion

  has_many :likings
  has_many :liked_opinions, through: :likings, source: :opinion

  def followed?(user)
    followers.include?(user)
  end

  def follows?(user)
    followeds.include?(user)
  end

  def followers_count
    followers.count
  end

  def followeds_count
    followeds.count
  end

  def opinions_count
    opinions.count
  end

  def owns?(opinion_id)
    opinions.any? { |op| op.id == opinion_id }
  end

  def owns_comment?(comment_id)
    comments.any? { |comment| comment.id == comment_id }
  end

  def judged?(opinion_id)
    opinions_likings.any? { |opinion| opinion.id == opinion_id }
  end

  def liked?(opinion_id)
    likings.any? { |liking| liking.opinion_id == opinion_id && liking.status == true }
  end

  def disliked?(opinion_id)
    likings.any? { |liking| liking.opinion_id == opinion_id && liking.status == false }
  end

  def opinion_feed
    followeds_ids = []
    followeds.includes(:photo_attachment).each { |f| followeds_ids << f.id }
    Opinion.where(author: (followeds_ids + [id])).includes(:author)
  end

  def follow_suggest
    (User.all.includes(:photo_attachment) - followeds - [User.find(id)])[0..2]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_already_signed_in, only: %i[new create]
  before_action :user_signed_in, except: %i[new create]

  def index
    @users = User.all_users_except_me(current_user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(sign_up_params)
    if @user.save
      session[:current_user] = @user.id
      flash[:notice] = 'Welcome ' + current_user.fullname
      redirect_to root_path
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def update
    if current_user.update(sign_up_params)
      flash[:notice] = 'Your account has been successfully updated'
      redirect_to current_user
    else
      flash[:errors] = current_user.errors.full_messages
      @user = current_user
      render :edit
    end
  end

  def follow
    followed = User.find(params[:id])
    following = current_user.sent_followings.build(followed_id: params[:id])
    if following.save
      flash[:notice] = 'You are now following ' + followed.username
    else
      flash[:errors] = following.errors.full_messages
    end
    redirect_to users_path
  end

  def unfollow
    followed = User.find(params[:id])
    following = Following.find_by(follower_id: current_user.id, followed_id: params[:id])
    if following.destroy
      flash[:notice] = 'You are no more following ' + followed.username
    else
      flash[:errors] = ['Could not unfollow']
    end
    redirect_to users_path
  end

  private

  def sign_up_params
    params.require(:user).permit(:username, :fullname, :photo, :cover_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def following_button(user)
    if current_user.follows?(user)
      render partial: 'users/follows_button', locals: { user: user }
    else
      render partial: 'users/follow_button', locals: { user: user }
    end
  end

  def edit_profile_button(user)
    link_to 'Update my profile', edit_user_path(user) if current_user.id == user.id
  end
end

app/views/users/_follow_button.html.erb
<%= link_to '', {controller: :users, action: :follow, id: user.id}, method: :post, class:"fa fa-plus-circle grey px-2" %>
<% if current_user.followed?(user) %>
    <i class="fa fa-users blue"></i>
<% end %>

app/views/users/_follows_button.html.erb
<i class="fa fa-users blue px-2"></i>
<%= link_to '', {controller: :users, action: :unfollow, id: user.id}, method: :delete, class: "fa fa-minus-circle grey" %>

app/views/users/_user.html.erb
<div class="row py-2">
    <div class="col-3 px-4">
       <%= image_tag user.photo.variant(resize_to_limit: [100, 100]), class: "user-pic" %> 
    </div>
    <div class="col-7">
        <%= link_to user.fullname, user_path(user), class: "text-dark small-text font-weight-bold" %>
        <p><small class="grey">@<%= user.username %> </small></p>
    </div>
    <div class="col-2">
        <%= following_button(user) %> 
    </div>
</div>

app/views/users/_user_form.html.erb
<%= form_with(model: @user, local: true) do |f|%>
    <div class="row field form-group">
        <%= f.label :fullname, class: "dark-grey" %>
        <%= f.text_field :fullname, class: "form-control" %>
    </div>

    <div class="row field form-group">
        <%= f.label :username, class: "dark-grey" %>
        <%= f.text_field :username, class: "form-control" %>
    </div>

    <div class="row field form-group">
        <%= f.label :photo, class: "dark-grey" %>
        <%= f.file_field :photo, class: "form-control", direct_upload: true %>
    </div>

    <div class="row field form-group">
        <%= f.label :cover_image, class: "dark-grey" %>
        <%= f.file_field :cover_image, class: "form-control", direct_upload: true %>
    </div>

    <div class="row field form-group">
        <%= f.submit 'Done', class: "btn bg-blue text-white" %>
    </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="col-9 d-flex flex-column grey-border-right">
    <div class="row">
        <%= image_tag @user.cover_image.variant(resize_to_limit: [700, 400]), class: "cover-image" %>
    </div>
    <div class="row grey-border-bottom justify-content-between p-4">
        <span class="dark-grey text-extra-medium font-weight-bolder">Update my profile</span>
    </div>
    <div class="row d-flex flex-column p-4">
        <div class="row bg-white grey-border rounded p-4 m-1">
            <%= render 'user_form' %>
        </div>
    </div>
</div>
<div class="col-3 d-flex flex-column ">
    <div class="row grey-border-bottom justify-content-center p-4">
        <%= image_tag @user.photo.variant(resize_to_limit: [100, 100]), class: "profile-pic rounded-circle"%>
        <div class="col d-flex flex-column py-2">
            <span class="text-dark text-center grey"><%= @user.fullname %></span>
            <span class="medium-text text-center grey">@<%= @user.username %></span>
        </div>
    </div>
    <div class="row grey-border-bottom">
        <div class="col-4 d-flex flex-column grey-border-right text-center py-2">
            <b class="text-dark big-text"><%= @user.opinions_count %></b>
            <span class="small-text dark-grey">Reviews</span>
        </div>
        <div class="col-4 d-flex flex-column grey-border-right text-center py-2">
            <b class="text-dark big-text"><%= @user.followeds_count %></b>
            <span class="small-text dark-grey">Following</span>
        </div>
        <div class="col-4 d-flex flex-column text-center py-2">
            <b class="text-dark big-text"><%= @user.followers_count %></b>
            <span class="small-text dark-grey">Followers</span>
        </div>
    </div>

    <div class="row px-4">
        <div class="col grey-border-bottom py-4 px-0">
            <span class="dark-grey text-extra-medium font-weight-bolder">FOLLOWED BY</span>
        </div>
        <div clas="col d-flex flex-column p-4">
            <% @user.followers.each do |user| %>
                <%= render user %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="col-9 d-flex flex-column grey-border-right">
    <div class="row grey-border-bottom p-4">
        <span class="dark-grey text-extra-medium font-weight-bolder">Follow some intersting reviewrs</span>
    </div>
    <div class="row d-flex flex-column p-4">
        <div class="col bg-white grey-border rounded px-5 mx-1 my-3">
            <div class="row grey-border-bottom py-4">
                <span class="blue text-medium font-weight-bolder"><%= @users.count %> Reviewer(s)</span>
            </div>
            <% @users.each do |user| %>
                <%= render user %>
            <% end %>
        </div>
    </div>
</div>
<div class="col-3 d-flex flex-column ">
    <% if current_user %>
        <div class="row grey-border-bottom px-4">
            <div class="col-12 grey-border-bottom py-4 px-0">
                <span class="dark-grey text-extra-medium font-weight-bolder">Who to follow</span>
            </div>
            <div clas="col-12 d-flex flex-column p-4">
                <% current_user.follow_suggest.each do |user| %>
                    <%= render user %>
                <% end %>
                <div class="p-2 blue">
                    <%= link_to 'Popular account', users_path, class: "blue small-text" %> <span> &#183; </span> 
                    <%= link_to 'Find friends', users_path, class: "blue small-text" %> 
                </div>
            </div>
        </div>
    <% end %>
    <div class="row px-4">
        <div class="col grey-border-bottom py-4 px-0">
            <span class="dark-grey text-extra-medium font-weight-bolder">Popular reviews</span>
        </div>
        <div clas="col d-flex flex-column p-4">
            <% most_popular_posts.values[0..2].each do |opinion| %>
                <div class="row py-2">
                    <div class="col-3 px-4">
                        <%= image_tag opinion.author.photo.variant(resize_to_limit: [100, 100]), class: "user-pic" %> 
                    </div>
                    <div class="col-7">
                        <%= link_to opinion.author.fullname, user_path(opinion.author), class: "text-dark small-text font-weight-bold" %>
                        <p><small class="grey"> review of <b class="blue"><%= opinion.book_name %></b>: <%= opinion.content.truncate(25) %></small></p>
                    </div>
                    <div class="col-2">
                        <%= link_to '', opinion_path(opinion), class: "fa fa-eye blue mx-2"%>
                    </div>
                </div>
            <% end %>
            <div class="p-2 blue">
                <%= link_to 'Make a review too', users_path, class: "blue small-text" %>
            </div>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<div class="col-12 d-flex flex-column">
    <div class="row grey-border-bottom p-4">
        <span class="dark-grey text-extra-medium font-weight-bolder">Sign up</span>
    </div>
    <div class="row d-flex flex-column p-4">
        <div class="row bg-white grey-border rounded p-4 m-1">
            <%= render 'user_form' %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="col-9 d-flex flex-column grey-border-right">
    <div class="row">
        <%= image_tag @user.cover_image.variant(resize_to_limit: [700, 400]), class: "cover-image" %>
    </div>
    <div class="row grey-border-bottom justify-content-between p-4">
        <a href="#feed"><span class="dark-grey text-extra-medium font-weight-bolder">Book reviews</span></a>
        <a href="#following"><span class="dark-grey text-extra-medium font-weight-bolder">Following</span></a>
        <a href="#follower"><span class="dark-grey text-extra-medium font-weight-bolder">Followers</span></a>
        <a href="#opinion"><span class="dark-grey text-extra-medium font-weight-bolder">Favourite reviews</span></a>
    </div>
    <div class="row d-flex flex-column p-4">
        <div class="col bg-white grey-border rounded px-5 mx-1 my-3" id="feed">
            <div class="row grey-border-bottom py-4">
                <span class="blue text-medium font-weight-bolder"><%= @user.opinions_count %> book review(s)</span>
            </div>
            <% @user.opinions.each do |opinion| %>
                <%= render opinion %>
            <% end %>
        </div>

        <div class="col bg-white grey-border rounded px-5 mx-1 my-3" id="following">
            <div class="row grey-border-bottom py-4">
                <span class="blue text-medium font-weight-bolder"><%= @user.followeds_count %> following(s)</span>
            </div>
            <% @user.followeds.each do |user| %>
                <%= render user %>
            <% end %>
        </div>

        <div class="col bg-white grey-border rounded px-5 mx-1 my-3" id="follower">
            <div class="row grey-border-bottom py-4">
                <span class="blue text-medium font-weight-bolder"><%= @user.followers_count %> follower(s)</span>
            </div>
            <% @user.followers.each do |user| %>
                <%= render user %>
            <% end %>
        </div>

        <div class="col bg-white grey-border rounded px-5 mx-1 my-3" id="opinion">
            <div class="row grey-border-bottom py-4">
                <span class="blue text-medium font-weight-bolder"><%= @user.liked_opinions.count %> favourite review(s)</span>
            </div>
            <div class="row py-4">
                <% @user.liked_opinions.each do |opinion| %>
                    <%= render opinion %>
                <% end %>
            </div>
        </div>
    </div>
</div>
<div class="col-3 d-flex flex-column ">
    <div class="row grey-border-bottom justify-content-center p-4">
        <% if current_user.followed?(@user) %>
            <%= link_to '', {controller: :users, action: :unfollow, id: @user.id}, method: :delete, class: "fa fa-minus-circle grey big-text my-auto mx-3" %>
        <% else %>
            <%= link_to '', {controller: :users, action: :follow, id: @user.id}, method: :post, class:"fa fa-plus-circle grey big-text my-auto mx-3" %>
        <% end %>
        <%= image_tag @user.photo.variant(resize_to_limit: [100, 100]), class: "profile-pic rounded-circle"%>
        <% if current_user == @user %>
            <%= link_to '', edit_user_path(@user), class: "fa fa-cog grey big-text my-auto mx-3" %>
        <% else %>
            <i class="fa fa-cog grey big-text my-auto mx-3"></i>
        <% end %>
        <div class="col d-flex flex-column py-2">
            <span class="text-dark text-center grey"><%= @user.fullname %></span>
            <span class="medium-text text-center grey">@<%= @user.username %></span>
        </div>
    </div>
    <div class="row grey-border-bottom">
        <div class="col-4 d-flex flex-column grey-border-right text-center py-2">
            <b class="text-dark big-text"><%= @user.opinions_count %></b>
            <span class="small-text dark-grey">Reviews</span>
        </div>
        <div class="col-4 d-flex flex-column grey-border-right text-center py-2">
            <b class="text-dark big-text"><%= @user.followeds_count %></b>
            <span class="small-text dark-grey">Following</span>
        </div>
        <div class="col-4 d-flex flex-column text-center py-2">
            <b class="text-dark big-text"><%= @user.followers_count %></b>
            <span class="small-text dark-grey">Followers</span>
        </div>
    </div>

    <div class="row px-4">
        <div class="col grey-border-bottom py-4 px-0">
            <span class="dark-grey text-extra-medium font-weight-bolder">FOLLOWED BY</span>
        </div>
        <div clas="col d-flex flex-column p-4">
            <% @user.followers.each do |user| %>
                <%= render user %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>