config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:destroy]
  resources :sessions, only: [:new, :create]
  resources :opinions do
    resources :comments, except: [:new, :index, :show]
    resources :likings, only: [:create, :update]
  end
  get '/sign-up', to: 'users#new'
  get '/sign-in', to: 'sessions#new'
  get '/sign-out', to: 'sessions#destroy'
  post '/follow/:id', to: 'users#follow'
  delete '/unfollow/:id', to: 'users#unfollow'
  root 'opinions#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/liking.rb
class Liking < ApplicationRecord
  belongs_to :opinion
  belongs_to :user

  validates :user_id, uniqueness: { scope: :opinion_id }
end

app/controllers/likings_controller.rb
class LikingsController < ApplicationController
  before_action :user_signed_in

  def create
    liking = Liking.new(status: params[:status])
    liking.opinion = Opinion.find(params[:opinion_id])
    liking.user = current_user
    if liking.save
      redirect_to root_path, notice: 'Thanks for judging this book review'
    else
      redirect_to root_path, errors: liking.errors.full_messages
    end
  end

  def update
    liking = Liking.find(params[:id])
    if liking.update(status: params[:status])
      redirect_to root_path, notice: 'You judgement has been updated'
    else
      redirect_to root_path, errors: liking.errors.full_messages
    end
  end
end

app/helpers/likings_helper.rb
module LikingsHelper
end

app/views/likings/_dislike_button.html.erb
<i class="fa fa-thumbs-up blue mx-2"></i>
<%= link_to '', opinion_liking_path(opinion, id: liking.id, status: false), method: :put, class: "fa fa-thumbs-down grey mx-2" %>

app/views/likings/_like_button.html.erb
<i class="fa fa-thumbs-down blue mx-2"></i>
<%= link_to '', opinion_liking_path(opinion, id: liking.id, status: true), method: :put, class: "fa fa-thumbs-up grey mx-2" %>

app/views/likings/_liking_buttons.html.erb
<%= link_to '', opinion_likings_path(opinion, status: true), method: :post, class: "fa fa-thumbs-up grey mx-2" %>
<%= link_to '', opinion_likings_path(opinion, status: false), method: :post, class: "fa fa-thumbs-down grey mx-2" %>